name: CI / Snapshot

on:
    push:
        branches:
            - master
            - 'feature/**'
            - 'bug/**'
            - 'fix/**'
            - 'hotfix/**'
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    snapshot:
        uses: oberon-oss/github-workflows/.github/workflows/maven-snapshot.yml@e2d11bf171adf6ba14145f7f3644de1dfe52e6ae
        with:
            java-version: '25'
            snapshot-branch: master
            sonar-enabled: true
            sonar-maven-profile: coverage
            snapshot-maven-profiles: generate-javadoc-and-source
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
            CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}