name: CI / Snapshot

on:
    push:
        branches:
            - master
            - 'feature/**'
            - 'bug/**'
            - 'fix/**'
            - 'hotfix/**'
    pull_request:
        branches:
            - master
    workflow_dispatch:

jobs:
    snapshot:
        uses: oberon-oss/github-workflows/.github/workflows/maven-snapshot.yml@bfb7933679c71bfc7387eac51784d2484706cdfd
        with:
            java-version: '25'
            snapshot-branch: master
            sonar-enabled: ${{ github.ref == 'refs/heads/master' || github.event_name == 'pull_request' }}
            sonar-maven-profile: coverage
            snapshot-maven-profiles: generate-javadoc-and-source
            sonar-project-key: eu.oberon-oss:picocli-option-help
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
            CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}