name: Publish package to Maven Central

on:
    release:
        types:
            - created

jobs:
    release:
        # v1.1
        uses: oberon-oss/github-workflows/.github/workflows/maven-release.yml@e2d11bf171adf6ba14145f7f3644de1dfe52e6ae
        with:
            java-version: '25'
            release-maven-profiles: central-release,generate-javadoc-and-source
        secrets:
            CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
            CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}